name: Auto Tests
on: [push]
env:
  TEST_MERGIN_URL: https://app.dev.merginmaps.com/
  TEST_API_USERNAME: test_plugin
  TEST_API_PASSWORD: ${{ secrets.MERGINTEST_API_PASSWORD }}
  TEST_API_USERNAME2: test_plugin2
  TEST_API_PASSWORD2: ${{ secrets.MERGINTEST_API_PASSWORD2 }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install python package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil pytz pytest pytest-cov pygeodiff coveralls

      - name: Run tests
        run: |
          pytest --cov=mergin mergin/test/

      - name: Submit coverage to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
